# Generated by Django 4.2.4 on 2023-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_name', models.CharField(max_length=255)),
                ('registration_email', models.CharField(max_length=255)),
                ('registration_num', models.CharField(max_length=255, null=True)),
                ('registration_use', models.CharField(max_length=255, null=True)),
                ('registration_pass', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
